version: '3'
services:
  web:
    build: ./
    ports:
      - '8888:80'
    expose:
      - "80"
      - "9000"
    volumes:
      - ./:/var/www/html/
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: 'yii2-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yii2
      MYSQL_DATABASE: yii2
      MYSQL_USER: yii2
      MYSQL_PASSWORD: yii2
    volumes:
      - ./config/:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'yii2-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions
